version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Todo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  express:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres-data:
